name: weather
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_riverpod: ^2.0.0  # Ensure this line is properly indented
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.11 # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
